### ISSUE TITLE
DNS Problem

### ISSUE THREAD

**Issue by zsunberg** [CU-ADCL/CU-ADCL.github.io#10]
I am getting this in chrome:
![image](https://user-images.githubusercontent.com/4240491/174867251-675cecef-f0f8-4007-a9d8-570e8c4bf272.png)
(but not on firefox - weird)

**Comment by qhho** [comment]
I am also getting this same issue on chrome. It probably has to do with some settings on the domain server.

**Comment by zsunberg** [comment]
This is fixed for me. Closing. @himanshugupta1009 @qhho can you confirm that it is fixed?

**Comment by himanshugupta1009** [comment]
It's not fixed for me yet. Did clearing the cache yesterday did the trick or did you do something else?

**Comment by zsunberg** [comment]
@himanshugupta1009 does the website load for you now?

**Comment by zsunberg** [comment]
I think this is fixed
