### ISSUE TITLE
Add link about grfp to news entry

### ISSUE THREAD

**Issue by zsunberg** [CU-ADCL/CU-ADCL.github.io#19]
@bkraske this is a simple exercise to get you used to working with the website:

There is a news entry about your grfp. Please add a link from that news entry to this announcement page:
https://www.colorado.edu/aerospace/2022/04/12/five-cu-boulder-aerospace-students-earn-major-nsf-graduate-research-fellowships

Once you are done, close the issue. Thanks!

**Comment by bkraske** [comment]
The link is up: https://github.com/CU-ADCL/CU-ADCL.github.io/commit/f0afda8d6eba4f9134ebf880e5b5bad69f279592

**Comment by zsunberg** [comment]
Thanks!
