### ISSUE TITLE
Add blurb about Tyler's AMOS poster on News page

### ISSUE THREAD

**Issue by zsunberg** [CU-ADCL/CU-ADCL.github.io#26]
@WhiffleFish can you add a blurb about your AMOS poster on the news page by the end of this week? Thanks

**Comment by WhiffleFish** [comment]
Still waiting on AMOS 2022 archive to drop to be able to link the work

**Comment by zsunberg** [comment]
@WhiffleFish looks like the papers are posted - can you add the appropriate links by the end of this week?
