### ISSUE TITLE
Add Jackson's AMOS publication

### ISSUE THREAD

**Issue by zsunberg** [CU-ADCL/CU-ADCL.github.io#28]
@the-one-and-only-jackson Can you please add your AMOS publication to the bib file by the end of the week?

**Comment by zsunberg** [comment]
Please also add a blurb to the news list about your presentation

**Comment by zsunberg** [comment]
Hi @the-one-and-only-jackson , it appears the AMOS publications are posted. Can you add a link to the bib file and news file by the end of this week?

**Comment by the-one-and-only-jackson** [comment]
The URLs for both AMOS papers have been added

**Comment by zsunberg** [comment]
Thanks @the-one-and-only-jackson ! In the future, please close issues once they are completed, thanks.
