### ISSUE TITLE
Add blurb about workshop to News

### ISSUE THREAD

**Issue by zsunberg** [CU-ADCL/CU-ADCL.github.io#43]
Can someone please add a blurb about our workshop to the NEWS page?

**Comment by himanshugupta1009** [comment]
Just added it. Let me know if you find any problems in it or can't see it!

**Comment by zsunberg** [comment]
@himanshugupta1009 I don't see it: 
![image](https://github.com/CU-ADCL/CU-ADCL.github.io/assets/4240491/39d8217f-d532-46cf-8695-9dd90fc0e7a8)

**Comment by himanshugupta1009** [comment]
![Screenshot from 2023-09-14 22-56-43](https://github.com/CU-ADCL/CU-ADCL.github.io/assets/57426103/b4a6180e-9b3d-4613-aa3e-7f6eaa2cda93)

It is visible now. Fixed the issue.

**Comment by zsunberg** [comment]
Great, thanks, @himanshugupta1009 !
