### ISSUE TITLE
ICRA paper in NEWS and our-pubs.bib

### ISSUE THREAD

**Issue by zsunberg** [CU-ADCL/CU-ADCL.github.io#51]
@zlaouar can you make sure to add the ICRA publication to NEWS and take care of any other things mentioned here: https://www.cu-adcl.org/posts/publication-checklist/

**Comment by zlaouar** [comment]
Just added it!

**Comment by zlaouar** [comment]
The site doesn't seem to be building. The error: ``extract_excerpt': undefined method `excerpt_separator' for #<Jekyll::Page @name=404.md`
